INSERT INTO ALIEN (AID, A_NAME, TECH) VALUES (101, 'Pratik', 'JavaScript');
INSERT INTO ALIEN (AID, A_NAME, TECH) VALUES (102, 'Vengu', 'MBA');
INSERT INTO ALIEN (AID, A_NAME, TECH) VALUES (103, 'Bhramesh', 'Enterprenuer');
INSERT INTO ALIEN (AID, A_NAME, TECH) VALUES (104, 'Sarvesh', 'Blockchain');
INSERT INTO ALIEN (AID, A_NAME, TECH) VALUES (105, 'Rahul', 'Java');